name: continuous integration and deployment

on:
  push:
    branches:
      - master
  pull_request:
  pull_request_review:
    types: [submitted]
  workflow_dispatch:
  release:
    types: [created]

concurrency:
  # prevent duplicate runs
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # https://nodejs.org/en/about/previous-releases#release-schedule
        node: [24]

    steps:
      - # https://github.com/actions/checkout
        name: Check out repository
        uses: actions/checkout@v7

      - # https://github.com/actions/setup-node
        name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies from package-lock.json
        run: npm clean-install

      - name: Check linter
        run: npm run lint

      - name: Check for proper formatting
        run: npm run format-check

      - name: Check if build succeeds
        run: npm run build

      - # this runs vitest in a non-interactive shell, so watch mode is disabled automatically (no need to add --run)
        # https://vitest.dev/config/watch
        name: Run tests
        run: npm run test

  publish:
    # skip this job for pull request updates (it *will* run on review submission, push to master, and release creation)
    if: ${{ github.event_name != 'pull_request' }}
    needs: check
    uses: FAIRDataTeam/github-workflows/.github/workflows/docker-publish.yml@v3
    secrets: inherit
    with:
      file: './Dockerfile'
      # only publish to docker hub when triggered by push to master branch or release creation
      push: ${{ github.event_name == 'push' || github.event_name == 'release' }}
